# Generated by Django 4.0 on 2022-01-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisttocustomer', to='User.customer'),
        ),
        migrations.AddField(
            model_name='property',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propertytocat', to='Product.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producttocat', to='Product.category'),
        ),
        migrations.AddField(
            model_name='details',
            name='pro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailstoproperty', to='Product.property'),
        ),
        migrations.AddField(
            model_name='details',
            name='product_id',
            field=models.ManyToManyField(to='Product.Product'),
        ),
        migrations.AddField(
            model_name='category',
            name='sub_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cattocat', to='Product.category'),
        ),
    ]
