# Generated by Django 4.0 on 2022-01-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
