# Generated by Django 4.0 on 2022-02-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_alter_wishlist_user'),
        ('Product', '0008_product_slug'),
    ]

    operations = [
    ]
