# Generated by Django 4.0 on 2022-02-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_userdevice_delete_usersession'),
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Main',
            new_name='Payment',
        ),
    ]
