# Generated by Django 4.0 on 2022-01-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cart', '0001_initial'),
        ('User', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='customer',
            field=models.ForeignKey(help_text='مشتری', on_delete=django.db.models.deletion.CASCADE, related_name='HistorytoCustomer', to='User.customer'),
        ),
        migrations.AddField(
            model_name='cartme',
            name='product',
            field=models.ManyToManyField(help_text='کالاها', through='Cart.CartItem', to='Product.Product'),
        ),
        migrations.AddField(
            model_name='cartme',
            name='user',
            field=models.ForeignKey(help_text='نام کاربری', on_delete=django.db.models.deletion.CASCADE, related_name='CartmetoCustomer', to='User.customer'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(help_text='سبد خرید', on_delete=django.db.models.deletion.CASCADE, related_name='CartItemtoCartMe', to='Cart.cartme'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(help_text='کالاها', on_delete=django.db.models.deletion.CASCADE, related_name='CartItemtoProduct', to='Product.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='cartitemtosels', to='User.salesman'),
        ),
    ]
