# Generated by Django 4.0 on 2022-01-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartme',
            name='discount',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='discount'),
        ),
    ]
