# Generated by Django 4.0 on 2022-01-17 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_alter_cartme_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='cartme',
        ),
    ]
