# Generated by Django 4.0 on 2022-01-19 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_profile_address_profile_postal_code'),
        ('Cart', '0004_remove_history_cartme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='customer',
            field=models.ForeignKey(help_text='مشتری', on_delete=django.db.models.deletion.CASCADE, related_name='HistorytoCustomer', to='User.profile'),
        ),
    ]
