# Generated by Django 4.0 on 2022-01-11 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address_db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User.address'),
        ),
    ]
