# Generated by Django 4.0 on 2022-01-11 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_profile_address_db'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address_db',
        ),
    ]
