# Generated by Django 4.0 on 2022-01-11 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_profile_address_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
