# Generated by Django 4.0 on 2022-01-26 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_usersession_browser_usersession_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=150, null=True)),
                ('browser', models.CharField(max_length=150, null=True)),
                ('os', models.CharField(max_length=150, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='User.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
