# Generated by Django 4.0 on 2022-01-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, help_text='کامنت خود را وارد کنید', max_length=255, null=True, verbose_name='comment')),
            ],
            options={
                'verbose_name': 'comment',
                'verbose_name_plural': 'comments',
            },
        ),
        migrations.CreateModel(
            name='rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], help_text='امتیاز خود را وارد کنید', max_length=1, null=True, verbose_name='rate')),
            ],
            options={
                'verbose_name': 'rate',
                'verbose_name_plural': 'rates',
            },
        ),
    ]
