# Generated by Django 4.0 on 2022-01-08 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Comment', '0002_initial'),
        ('User', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratetocustomer', to='User.customer', verbose_name='user'),
        ),
        migrations.AddField(
            model_name='commentme',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenttoproduct', to='Product.product', verbose_name='product'),
        ),
        migrations.AddField(
            model_name='commentme',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenttouser', to='User.customer', verbose_name='comment'),
        ),
    ]
