# Generated by Django 4.0 on 2022-02-07 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_userdevice_delete_usersession'),
        ('Comment', '0004_alter_commentme_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentme',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commenttouser', to='User.profile', verbose_name='comment'),
        ),
    ]
