# Generated by Django 4.0 on 2022-01-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_news', models.ImageField(blank=True, help_text='تصویر خود را آپلود کنید ', null=True, upload_to='Notification/News', verbose_name='image')),
                ('file_news', models.FileField(blank=True, help_text='فایل خود را آپلود کنید ', null=True, upload_to='Notification/News', verbose_name='file')),
                ('text_new', models.TextField(help_text='توضیحات مربوطه', verbose_name='Text')),
            ],
            options={
                'verbose_name': 'News',
            },
        ),
        migrations.CreateModel(
            name='notif_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_notif', models.ImageField(blank=True, help_text='تصویر خود را آپلود کنید ', null=True, upload_to='Notification/notif_user', verbose_name='image')),
                ('file_notif', models.FileField(blank=True, help_text='فایل خود را آپلود کنید ', null=True, upload_to='Notification/notif_user', verbose_name='file')),
                ('text_notif', models.TextField(help_text='توضیحات مربوطه', verbose_name='Text')),
            ],
            options={
                'verbose_name': 'notif_user',
                'verbose_name_plural': 'notif_users',
            },
        ),
    ]
