# Generated by Django 4.0 on 2022-01-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Notify', '0001_initial'),
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notif_user',
            name='product',
            field=models.ManyToManyField(to='Product.Product'),
        ),
    ]
